project:
  type: website
  output-dir: docs

website:
  title: "Modules de soutien statistique 2025–2026"
  page-navigation: true
  search: true
  repo-url: https://github.com/amaltawfik/modules-soutien-statistique-hesav
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Accueil
      - text: Présentations
        menu:
          - text: "Introduction à R et RStudio : premiers pas, bonnes pratiques et workflow"
            href: 01-intro_r_rstudio/index.qmd
          - text: "Nettoyage et manipulation des données avec R : introduction au tidyverse"
            href: 02-clean_manipulation/index.qmd
          - text: "Analyses bivariées : tableaux croisés, comparaison de moyennes, analyse de variance, corrélation"
            href: 03-analyses_bivariees/index.qmd
          - text: "Régression linéaire : principes, interprétation et visualisation des résultats"
            href: 04-regression_lineaire/index.qmd
          - text: "Analyses factorielles exploratoires (EFA) et construction d’échelles : fondements et mise en œuvre"
            href: 05-efa_echelles/index.qmd
          - text: "Visualisation des données avec ggplot2 : grammaire graphique et bonnes pratiques"
            href: 06-visualisation/index.qmd
          - text: "Régression logistique : interprétation, ajustement et qualité du modèle"
            href: 07-regression_logistique/index.qmd

format:
  # ---- Présentations revealjs ----
  revealjs:
    theme: [simple, dark]             # clair + sombre
    slide-number: true
    toc: true
    transition: fade
    link-external-newwindow: true     # ouvre les liens externes dans un nouvel onglet
    lightbox: true                    # agrandit les images au clic
    code-overflow: scroll
    code-line-numbers: false
    chalkboard:
      buttons: true
      theme: whiteboard

  # ---- Pages HTML du site ----
  html:
    theme:
      light: flatly
      dark: darkly
    bootstrap: 5
    light-switch: true
    link-external-newwindow: true     # ouvre les liens externes dans un nouvel onglet
    lightbox: true                    # agrandit les images sur le site aussi
    bslib:
      info: "#4F4F52"
      base_font:
        google: {family: "Atkinson Hyperlegible", wght: [300, 400, 700], ital: [0, 1]}
      headings-color: "#2e2e2e"
      link-color: "#2e2e2e"
      link-decoration: underline dotted
    css: styles/custom.scss

execute:
  enabled: true
