project:
  type: website
  output-dir: docs

website:
  title: "Modules de soutien statistique 2025-2026"
  page-navigation: true
  search: true
  navbar:
    background: primary
    right:
      - github
    left:
      - href: index.qmd
        text: Accueil
      - text: Présentations
        menu:
          - text: "Introduction à R et RStudio : premiers pas, bonnes pratiques et workflow"
            href: 01-intro_r_rstudio/index.qmd
          - text: "Nettoyage et manipulation des données avec R : introduction au tidyverse"
            href: 02-clean_manipulation/index.qmd
          - text: "Analyses bivariées : tableaux croisés, comparaison de moyennes, analyse de variance, corrélation"
            href: 03-analyses_bivariees/index.qmd
          - text: "Régression linéaire"
            href: 04-regression_lineaire/index.qmd
          - text: "Analyses factorielles exploratoires (EFA) et construction d’échelles"
            href: 05-efa_echelles/index.qmd
          - text: "Visualisation des données avec ggplot2"
            href: 06-visualisation/index.qmd
          - text: "Régression logistique"
            href: 07-regression_logistique/index.qmd

format:
  revealjs:
    theme: [simple, dark]   # clair + sombre pour les présentations
    slide-number: true
    toc: true
    embed-resources: true
    transition: fade
    link-external-newwindow: true

  html:
    theme:
      light: flatly
      dark: darkly
    bootstrap: 5
    light-switch: true
    bslib:
      info: "#4F4F52"
      base_font:
        google: {family: "Atkinson Hyperlegible", wght: [300, 400, 700], ital: [0, 1]}
      headings-color: "#2e2e2e"
      link-color: "#2e2e2e"
      link-decoration: underline dotted
    css: styles/custom.scss  

